default:
  app_name: "custom_sign_in"
  firebase:
    apiKey: "<your Firebase project API Key>"
    authDomain: "<your Firebase project auth domain>"
    projectId: "<your Firebase project Id>"
  api_key: